# Generated by Django 4.0.4 on 2022-07-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallethistory_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='credit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='debit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='updated_amount',
            field=models.FloatField(),
        ),
    ]
