# Generated by Django 4.0.4 on 2022-06-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_pathdetail_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='distance',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
