# Generated by Django 4.0.4 on 2022-07-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_pathdetail_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepath',
            name='set_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepath',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
