# Generated by Django 4.0.4 on 2022-07-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehiclepath_set_time_vehiclepath_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepath',
            name='set_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiclepath',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
