# Generated by Django 4.0.4 on 2022-07-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehiclepath_date_created_vehiclepath_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathdetail',
            name='arrival_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='pathdetail',
            name='depature_time',
            field=models.DateTimeField(default=None),
        ),
    ]
